Mychem: conversion_wrapper.h File Reference
conversion_wrapper.h File Reference
#include <mychem/structures.h>
Functions
char * conversion (const char *molecule, const char *in_type, const char *out_type)
char * conversionSMA (const char *molecule, const char *inType)
char * V3000conversion (const char *V3000)
char * conversionV3000 (const char *molecule)
char * CMLconversion (const char *cml)
char * conversionCML (const char *molecule)
char * conversionFPT (const char *molecule, const char *type)
char * conversionCAN (const char *molecule)
char * serializeMolecule (const char *molecule)
Detailed Description
Wrapper for the Mychem conversion module.
This file is part of the Mychem software. It contains function declarations related to chemical file conversion.
Author
Jerome Pansanel jerom.nosp@m.e.pa.nosp@m.nsane.nosp@m.l@ip.nosp@m.hc.cn.nosp@m.rs.f.nosp@m.r
Aurelie De Luca aurel.nosp@m.iede.nosp@m.luca@.nosp@m.gmai.nosp@m.l.com
Function Documentation
conversion()
char* conversion (const char * molecule, const char * in_type, const char * out_type)
Converts a file format to an other.
Parameters
molecule The molecule to convert.
in_type Input format.
out_type Output format.
Returns
converted molecule
References LibHandler::isLoaded().
conversionSMA()
char* conversionSMA (const char * molecule, const char * inType)
Converts a file format to a smartslike SMILES.
Parameters
molecule The molecule to convert.
in_type Input format.
Returns
converted molecule
References LibHandler::isLoaded().
V3000conversion()
char* V3000conversion (const char * V3000)
Converts a V3000 molecule to the default molecule type.
Parameters
V3000 The V3000 molecule to convert.
Returns
converted molecule.
References LibHandler::isLoaded().
conversionV3000()
char* conversionV3000 (const char * molecule)
Converts a molecule to a V3000 molfile.
Parameters
molecule The molecule to convert.
Returns
V3000 molecule.
References LibHandler::isLoaded().
CMLconversion()
char* CMLconversion (const char * cml)
Converts a cml molecule to the default molecule type.
Parameters
cml The cml molecule to convert.
Returns
the converted cml.
References LibHandler::isLoaded().
conversionCML()
char* conversionCML (const char * molecule)
Converts a molecule to a cml molecule.
Parameters
molecule The cml molecule to convert.
Returns
the converted molecule.
References LibHandler::isLoaded().
conversionFPT()
char* conversionFPT (const char * molecule, const char * type)
Converts a molecule to a fingerprint.
Parameters
molecule The molecule to convert.
type The type of fingerprint (FP2, FP3 or FP4).
Returns
The fingerprint.
References LibHandler::isLoaded().
conversionCAN()
char* conversionCAN (const char * molecule)
Converts a molecule to a canonical SMILES.
Parameters
molecule The molecule to convert.
Returns
the canonical SMILES.
References LibHandler::isLoaded().
serializeMolecule()
char* serializeMolecule (const char * molecule)
Converts a molecule to a 1D serialized OBMol object.
Parameters
molecule The molecule to convert.
Returns
the serialized OBMol object.
References LibHandler::isLoaded(), and serializeOBMol().