Mychem: modification_wrapper.cpp File Reference
modification_wrapper.cpp File Reference
#include "modification_wrapper.h"
#include <mychem/config.h>
#include <mychem/dlhandler.h>
#include <openbabel/mol.h>
#include <openbabel/obconversion.h>
#include <sstream>
Functions
char * ob_add_hydrogens (const char *molecule)
char * ob_remove_hydrogens (const char *molecule)
char * ob_strip_salts (const char *molecule)
Detailed Description
Mychem Modification Wrapper.
This file is part of the Mychem software. It contains functions related to molecule modifications.
Author
Jerome Pansanel jerom.nosp@m.e.pa.nosp@m.nsane.nosp@m.l@ip.nosp@m.hc.cn.nosp@m.rs.f.nosp@m.r
Aurelie De Luca aurel.nosp@m.iede.nosp@m.luca@.nosp@m.gmai.nosp@m.l.com
Function Documentation
ob_add_hydrogens()
char* ob_add_hydrogens (const char * molecule)
Adds the hydrogen atoms of a molecule.
Parameters
molecule The molecule where to add hydrogens.
Returns
The modified molecule.
References LibHandler::isLoaded().
ob_remove_hydrogens()
char* ob_remove_hydrogens (const char * molecule)
Removes the hydrogen atoms of a molecule.
Parameters
molecule The molecule where to remove hydrogens.
Returns
The modified molecule.
References LibHandler::isLoaded().
ob_strip_salts()
char* ob_strip_salts (const char * molecule)
Removes all atoms except for the larger contiguous fragment.
Parameters
molecule The molecule where to remove the salts.
Returns
The cleaned molecule.
References LibHandler::isLoaded().