Mychem: molmatch_wrapper.h File Reference
molmatch_wrapper.h File Reference
Functions
long long match_substructure (const char *smarts_pattern, const char *serializedMolecule)
char * substructure_atom_ids (const char *smarts_pattern, const char *serializedMolecule)
long long substructure_count (const char *smarts_pattern, const char *serializedMolecule)
Detailed Description
Wrapper for the Mychem molmatch module.
This file is part of the Mychem software. It contains function declarations related to chemical file comparison.
Author
Jerome Pansanel jerom.nosp@m.e.pa.nosp@m.nsane.nosp@m.l@ip.nosp@m.hc.cn.nosp@m.rs.f.nosp@m.r
Aurelie De Luca aurel.nosp@m.iede.nosp@m.luca@.nosp@m.gmai.nosp@m.l.com
Bjoern Gruening bjoer.nosp@m.n@gr.nosp@m.uenin.nosp@m.gs.e.nosp@m.u
Function Documentation
match_substructure()
long long match_substructure (const char * smarts_pattern, const char * serializedMolecule)
Checks if a molecule is a substructure of an other molecule.
Parameters
smarts_pattern The molecule to check (SMARTS format)
serializedMolecule The reference molecule (serialized OBMol object)
Returns
1 if query is a substructure of reference
References LibHandler::isLoaded(), and unserializeOBMol().
substructure_atom_ids()
char* substructure_atom_ids (const char * smarts_pattern, const char * serializedMolecule)
Returns the atom ids of the reference molecule's atoms that are contained in substructures matching the query.
Parameters
smarts_pattern The molecule to check (SMARTS format)
serializedMolecule The reference molecule (serialized OBMol object)
Returns
The list of atom ids
References LibHandler::isLoaded(), and unserializeOBMol().
substructure_count()
long long substructure_count (const char * smarts_pattern, const char * serializedMolecule)
Returns the number of substructures within a reference structure.
Parameters
smarts_pattern The substructure to check (SMARTS format)
serializedMolecule The reference structure (serialized OBMol object)
Returns
The number of substructure
References LibHandler::isLoaded(), and unserializeOBMol().